### ISSUE TITLE
request: add maxexport.com provider.

### ISSUE THREAD

**Issue by takedowndmca** [hansputera/tiktok-dl#5]
I got another downloader site which is quite complete and fast

[Mav Export | TikTok Video Downloader](https://mavexport.com/)

**Comment by OhYoonHee** [comment]
@takedowndmca

**Comment by hansputera** [comment]
Hello there, thank you for making a request to add a website as the provider of this project.
Sorry, I can't add it now because there are some issues. And, what's that? That's a captcha. 

This website requires a captcha token response in each POST request. And, captcha tokens are generated on the client side.
When you submit a request with a post method to the website without a captcha token or wrong token. It will return an "Unauthorized Access" error in the URL. 

As much as possible, we won't use the [puppeteer](https://npmjs.com/package/puppeteer) module or anything like that.
Any ideas?
