### ISSUE TITLE
Maximum requests reached

### ISSUE THREAD

**Issue by cantonalex** [hansputera/tiktok-dl#8]
API doesnt seem to work says maximum requests made

**Comment by hansputera** [comment]
Any screenshots?

**Comment by cantonalex** [comment]
yes its a ratelimit response. Is there any way to download directly from tiktok's cdn without using an intermediary host?

**Comment by hansputera** [comment]
If you get a ratelimit response, please wait for 60 seconds/minute to use. If you want to remove it, you can fork this repository, and turn off ratelimit in "config.ts". Also, don't forget to fill REDIS URL. 

Currently, in this project, we are focused on downloading tiktok videos from intermediary hosts. Because, to download TikTok videos from tiktok's official cdn, secret credentials (sessionid, etc.) are required.

**Comment by cantonalex** [comment]
Thanks for your response. Do you know if utilising these sites contributes to their organic SEO ranking? Or are server unknown to Google.

**Comment by hansputera** [comment]
I don't know.
